{{- range .Values.config.projects }}
{{ $mangedNamespace := .managedNamespace }}
{{- range .namespaces }}
{{- if .create }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    kubernetes.io/metadata.name: {{ .namespace }}
    argocd.argoproj.io/managed-by: {{ $mangedNamespace }}
  name: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}