# ServiceMonitors: monitoring metrics from the main ArgoCD components
{{ $components := list "repo-server" "metrics" "server-metrics" }}
{{- range $components }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ $.Values.config.names.base }}-{{ . }}-monitor"
  namespace: {{ $.Values.config.argocdNamespace | quote }} 
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ $.Values.config.names.base }}-{{ . }}"
  endpoints:
  - port: metrics
{{- end }}

