{{- range .Values.config.projects }}
{{- range .namespaces }}
{{- if .create }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    kubernetes.io/metadata.name: {{ .namespace }}
    argocd.argoproj.io/managed-by: {{ $.Values.config.bootstrap.argocdNamespace }}
  name: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}
