# ArgoCD Application: Managing Tekton pipeline
{{- if .Values.config.tekton.enabled }}
{{- range .Values.config.projects }}
{{ $mangedNamespace := .managedNamespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .name }}-tekton"
  #namespace: {{ $.Values.config.argocdNamespace | quote }} 
  namespace: {{ $mangedNamespace | quote }} 
  #namespace: "openshift-gitops" 
spec:
  project: "{{ .name }}-prj"
  #project: "default"
  source:
    repoURL: https://github.com/haf-tech/quarkus-playground.git
    targetRevision: 'main'
    path: '.tekton/cicd/overlays'    
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{ $mangedNamespace }}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}