# CI Pipeline for application
# - git clone, in a subdir "src"
# - build with maven
# - sonarqube scan
# - build/package image with buildah
# 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: ci-pipeline-promote
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  params:
  - name: REPO
    type: string
  - name: COMMIT_SHA
    type: string
  - name: TLSVERIFY
    type: string
  - name: BUILD_EXTRA_ARGS
    type: string
  - name: DOCKERFILE
    type: string
  - name: IMAGE
    description: Image url (incl. tag/version) for a internal CR
    type: string
  - name: IMAGE_REMOTE_CR
    description: Image url (incl. tag/version) for a remote CR
    type: string
  - name: GIT_REF
    type: string
  - name: COMMIT_DATE
    type: string
  - name: COMMIT_AUTHOR
    type: string
  - name: COMMIT_MESSAGE
    type: string
  - name: GIT_REPO
    type: string
  - name: GIT_CONFIG_REPO
    type: string
  - name: GIT_CONFIG_REF
    type: string
  - name: MAVEN_GOALS
    type: array
  - name: SONAR_ENABLED
    type: string
    default: "false"
  - name: SONAR_PROJECT_KEY
    type: string
  - name: SONAR_TOKEN_SECRET_NAME
    type: string
  - name: IMAGE_SCAN_ENABLED
    type: string
    default: "true"
  - name: REMOTE_CR_PUSH_ENABLED
    type: string
    description: If tag and push to a remote CR is wanted or not
    default: "true"
  - name: PROMOTE_VERSION_ENABLED
    type: string
    description: If promoting version back to git is wanted
    default: "true"
  tasks:
  # ##################
  # Git clone manifest
  
  # ##################
  # Promote version and push back to git
  - name: promote-version
    params:
    - name: GIT_URL
      value: $(params.GIT_CONFIG_REPO)
    - name: GIT_REVISION
      value: $(params.GIT_CONFIG_REF)
    - name: CONTEXT_DIR
      value: 'src_manifest'
    - name: IMAGE_DIGEST
      value: 'aaaaa'
    - name: FILES
      value: 
      - 'helm/values.dev.yaml'
    - name: EXPRESSION
      value: '.image.digest="sha256:3663791abc50c432fd8c214ce8a5197f6e44ca80a0600c4352ddc7e173450a9b"'
    runAfter:
    - clone-manifest
    when:
      - input: "$(params.PROMOTE_VERSION_ENABLED)"
        operator: in
        values: ["true"]
    taskRef:
      kind: Task
      name: promote-version
    workspaces:
    - name: source
      workspace: shared-data
  workspaces:
  - description: This workspace will receive the cloned git repo.
    name: shared-data
  - description: This workspace will hold the Maven Settings (temp dir).
    name: maven-settings
  - description: This workspace will hold the SonarQube Settings (temp dir).
    name: sonar-settings
