apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-registry-cicd-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: default
