apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "-85"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - patch
  - get
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
  - patch
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - patch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - argocds
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - patch
