# PipelineRun example to execute Pipeline "maven-ci-pipeline"
# to build and package Quarkus app‚
# 
# Tekton Pipelines: v0.24.3
# Tekton Triggers: v0.14.2
# ClusterTasks based on Tekton Catalog 0.24
#
# apply with "create", otherwise the name will not be generated
# oc create -f pipelinerun-maven-ownerref.yaml
#
# This configuration holds an "ownerReferences" block. This is necessary in an ArgoCD environment
# otherwise ArgoCD will immediately remove this created instance, because this manually created and not managed
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: quarkus-build-run-
  ownerReferences:
    - apiVersion: tekton.dev/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Pipeline
      name: ci-pipeline-maven-buildah
      uid: b54d6dd1-d9b9-4173-a629-fa264aff4fb6
spec:
  params:
    - name: REPO
      value: "quarkus-playground"
    - name: GIT_REPO
      value: "https://github.com/haf-tech/quarkus-playground"
    - name: TLSVERIFY
      value: "false"
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: DOCKERFILE
      value: "./src/main/docker/Dockerfile.jvm"
    - name: IMAGE
      value: "image-registry.openshift-image-registry.svc:5000/demo-quarkus-cicd/quarkus-playground:latest"
    - name: APP_IMAGE_BASE
      value: ""
    - name: APP_IMAGE_TAGS
      value: 
        - "main-latest"
        - "latest"
    - name: MAVEN_GOALS
      #value: "package -Dmaven.test.skip=true"
      value: ["-Dmaven.test.skip=false", "package"]
    - name: COMMIT_SHA
      value: "1233"
    - name: GIT_REF
      value: "main"
    - name: COMMIT_DATE
      value: "2021-09-26T11:04:15+00:00"
    - name: COMMIT_AUTHOR
      value: "code@haddouti.com"
    - name: COMMIT_MESSAGE
      value: "Test PipelineRun"
  pipelineRef:
    name: ci-pipeline-maven-buildah
  serviceAccountName: pipeline
  workspaces:
  - name: maven-settings
    emptyDir: {}
  - name: sonar-settings
    emptyDir: {}
  - name: shared-data
    persistentVolumeClaim:
      claimName: pipeline-repo-pvc
#  - name: shared-data
#    volumeClaimTemplate:
#      metadata:
#        creationTimestamp: null
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
#      status: {}
  