# PipelineRun example to execute Pipeline "maven-ci-pipeline"
# to build and package Quarkus app‚
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: quarkus-deploy-run-
spec:
  params:
    - name: REPO
      value: "quarkus-playground"
    - name: GIT_REPO
      value: "https://github.com/haf-tech/quarkus-playground"
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: "image-registry.openshift-image-registry.svc:5000/demo-quarkus-cicd/quarkus-playground-tekton:latest"
    - name: GIT_REF
      value: "main"
    - name: HELM_CHART_DIR
      value: "helm/quarkus-playground"
    - name: HELM_RELEASE_VERSION
      value: "v0.5.0"
    - name: HELM_RELEASE_NAME
      value: "quarkus-playground-tkn-test"
    - name: HELM_RELEASE_NAMESPACE
      value: "demo-quarkus-cicd"
    - name: HELM_VALUES_FILE
      value: "values.test.yaml"
    - name: HELM_OVERWRITE_VALUES
      value: "image.repository=image-registry.openshift-image-registry.svc:5000/demo-quarkus-cicd/quarkus-playground-tekton,image.tag=latest,ingress.basedomain=hcs-ocp-93ccca5014f3f64f6f228d0d086be7b3-0000.eu-de.containers.appdomain.cloud"
  pipelineRef:
    name: cd-pipeline-helm
  serviceAccountName: pipeline
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: pipeline-repo-pvc
#  - name: shared-data
#    volumeClaimTemplate:
#      metadata:
#        creationTimestamp: null
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
#      status: {}
  