# PipelineRun example to execute Pipeline "maven-ci-pipeline"
# to build and package Quarkus app‚
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: quarkus-pr
  generateName: quarkus-run-
spec:
  params:
    - name: REPO
      value: "quarkus-playground"
    - name: GIT_REPO
      value: "https://github.com/haf-tech/quarkus-playground"
    - name: TLSVERIFY
      value: "false"
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: DOCKERFILE
      value: "./src/main/docker/Dockerfile.jvm"
    - name: IMAGE
      value: "image-registry.openshift-image-registry.svc:5000/test/quarkus-playground-tekton:latest"
    - name: APP_IMAGE_BASE
      value: ""
    - name: APP_IMAGE_TAGS
      value: 
        - "main-latest"
        - "latest"
    - name: MAVEN_GOALS
      #value: "package -Dmaven.test.skip=true"
      value: ["-Dmaven.test.skip=true", "package"]
    - name: COMMIT_SHA
      value: "1233"
    - name: GIT_REF
      value: "main"
    - name: COMMIT_DATE
      value: "2021-09-26T11:04:15+00:00"
    - name: COMMIT_AUTHOR
      value: "code@haddouti.com"
    - name: COMMIT_MESSAGE
      value: "Test PipelineRun"
  pipelineRef:
    name: maven-ci-pipeline
  serviceAccountName: pipeline
  workspaces:
  - name: maven-settings
    emptyDir: {}
  - name: shared-data
    persistentVolumeClaim:
      claimName: pipeline-repo-pvc
#  - name: shared-data
#    volumeClaimTemplate:
#      metadata:
#        creationTimestamp: null
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
#      status: {}
  