apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-repo-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain 