# DEPRECATED
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: ci-dryrun-from-push-template
  #namespace: tekton101-cicd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  params:
  - default: main
    description: The git revision
    name: io.openshift.build.commit.ref
  - description: The specific commit SHA
    name: io.openshift.build.commit.id
  - description: The git repository url
    name: common.git.repo.url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: ci-dryrun-from-push-$(uid)
    spec:
      pipelineRef:
        name: ci-dryrun-from-push-pipeline
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(tt.params.io.openshift.build.commit.id)
          - name: url
            value: $(tt.params.common.git.repo.url)
          type: git
      serviceAccountName: pipeline
    status: {}
status: {}
