apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: ci-template-maven
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  params:
  - description: The image tag.
    name: imageTag
  - description: The git branch for this PR.
    name: io.openshift.build.commit.ref
  - description: the specific commit SHA.
    name: io.openshift.build.commit.id
  - description: The date at which the commit was made
    name: io.openshift.build.commit.date
  - description: The name of the github user handle that made the commit
    name: io.openshift.build.commit.author
  - description: The commit message
    name: io.openshift.build.commit.message
  - description: The git repository URL.
    name: common.git.repo.url
  - description: The GitHub repository for this PullRequest.
    name: fullname
  - description: The repository to push built images to.
    name: imageRepo
  - description: Enable image repository TLS certification verification.
    name: tlsVerify
  - description: Extra parameters passed for the push command when pushing images.
    name: build_extra_args
  - description: Custom Dockerfile.
    name: dockerFile
    default: "./src/main/docker/Dockerfile.jvm"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: ci-app-$(uid)
    spec:
      params:
      - name: REPO
        value: $(tt.params.fullname)
      - name: GIT_REPO
        value: $(tt.params.common.git.repo.url)
      - name: TLSVERIFY
        value: $(tt.params.tlsVerify)
      - name: BUILD_EXTRA_ARGS
        value: $(tt.params.build_extra_args)
      - name: DOCKERFILE
        value: $(tt.params.dockerFile)
      - name: IMAGE
        value: $(tt.params.imageRepo):$(tt.params.io.openshift.build.commit.ref)-$(tt.params.io.openshift.build.commit.id)
      - name: APP_IMAGE_BASE
        value: $(tt.params.imageRepo)
      - name: APP_IMAGE_TAGS
        value: 
         - $(tt.params.io.openshift.build.commit.ref)-$(tt.params.io.openshift.build.commit.id)
         - $(tt.params.imageTag)
      - name: MAVEN_GOALS
        #value: "package -Dmaven.test.skip=true"
        value: ["-Dmaven.test.skip=true", "package"]
      - name: COMMIT_SHA
        value: $(tt.params.io.openshift.build.commit.id)
      - name: GIT_REF
        value: $(tt.params.io.openshift.build.commit.ref)
      - name: COMMIT_DATE
        value: $(tt.params.io.openshift.build.commit.date)
      - name: COMMIT_AUTHOR
        value: $(tt.params.io.openshift.build.commit.author)
      - name: COMMIT_MESSAGE
        value: $(tt.params.io.openshift.build.commit.message)
      pipelineRef:
        name: ci-pipeline-maven-buildah
      serviceAccountName: pipeline
      workspaces:
      - name: maven-settings
        emptyDir: {}
      - name: shared-data
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
