# Application Governance Configuration
# Holds the basic configuration
# - namespaces

config:
  appset:
    enabled: false
  bootstrap:
    name: argo-project-gov
    repo: https://github.com/haf-tech/quarkus-playground.git
    branch: main
    path: '.argocd/argocd-app-template'
    helmValueFile: values.yaml
    argocdNamespace: openshift-gitops
    argocdProject: default
    #configJson: argocd/config.json    
  projects: 
    - name: demo-quarkus-app
      managedNamespace: demo-quarkus-cicd
      namespaces:
      - namespace: demo-quarkus-cicd
        create: true
      - namespace: demo-quarkus-test
        create: true
      - namespace: demo-quarkus-dev
        create: true
      - namespace: demo-quarkus-prod
        create: true

