# Application Governance Configuration
# Holds the basic configuration
# - namespaces
# - apps to configure cluster or entire app projects

# Open
# - AppSet for projects, instead of apps (to group all project related resources to one)
# - test cluster-config integration
# - Pipeline resources, part of default ArgoCD or project-scope/visibility (permission!)
# - Optimize Namespace configuration for DevOps Team (gov + app-tpl)

config:
  appset:
    enabled: false
  projects: 
    # Base configuration for all app teams and projects
    - name: gov-projects
      managedNamespace: demo-quarkus-cicd
      repo: https://github.com/haf-tech/quarkus-playground.git
      branch: main
      path: '.argocd/argocd-app-template'
      helmValueFile: values.yaml
      argocdNamespace: openshift-gitops
      argocdProject: default
      #configJson: argocd/config.json
      namespaces:
      - namespace: demo-quarkus-cicd
        create: true
      - namespace: demo-quarkus-test
        create: true
      - namespace: demo-quarkus-dev
        create: true
      - namespace: demo-quarkus-prod
        create: true
    # Common cluster configuration and capabilities for all teams/projects
    - name: gov-cluster-config
      managedNamespace: demo-quarkus-cicd
      repo: https://github.com/haf-tech/quarkus-playground.git
      branch: main
      path: '.argocd/governance'
      #helmValueFile: values.yaml
      argocdNamespace: openshift-gitops
      argocdProject: default
      configJson: cluster-configs.json
      namespaces: []