apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: gitops-webhook-event-listener-route
  #namespace: tekton101-cicd
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: el-cicd-event-listener-quarkus-playground
    weight: 100
  wildcardPolicy: None
