# Task: SonarQube Scanner
# Source: https://github.com/tektoncd/catalog/blob/main/task/sonarqube-scanner/0.2/sonarqube-scanner.yaml
# Tekton Hub: https://hub.tekton.dev/tekton/task/sonarqube-scanner
# v0.2 - enhanced
#
# Enhancements
# - add sonar.login support as parameter (from a Secret)
# - add context dir
# - script optimizations
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scanner
  labels:
    app.kubernetes.io/version: "0.2.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: "sonarqube scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    The following task can be used to perform static analysis on the source code
    provided the SonarQube server is hosted

    SonarQube is the leading tool for continuously inspecting the Code Quality and Security
    of your codebases, all while empowering development teams. Analyze over 25 popular
    programming languages including C#, VB.Net, JavaScript, TypeScript and C++. It detects
    bugs, vulnerabilities and code smells across project branches and pull requests.

  workspaces:
    - name: source
    - name: sonar-settings
  params:
    - name: SONAR_HOST_URL
      description: Host URL where the sonarqube server is running
      default: ""
    - name: SONAR_PROJECT_KEY
      description: Project's unique key
      default: ""
    - name: SONAR_TOKEN_SECRET_NAME
      description: Secret name holding Token for sonar.login
      default: ""
    - name: SONAR_TOKEN
      description: Token for sonar.login
      default: ""
    - name: CONTEXT_DIR
      description: Context dir, default src
      default: "src"
  steps:
    - name: sonar-properties-create
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      env:
      - name: SONAR_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.SONAR_TOKEN_SECRET_NAME)
            key: 'token'
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        #!/usr/bin/env bash

        replaceValues() {
          filename=$1
          thekey=$2
          newvalue=$3

          if ! grep -R "^[#]*\s*${thekey}=.*" $filename >/dev/null; then
            echo "APPENDING because '${thekey}' not found"
            echo "" >>$filename
            echo "$thekey=$newvalue" >>$filename
          else
            echo "SETTING because '${thekey}' found already"
            sed -ir "s|^[#]*\s*${thekey}=.*|$thekey=$newvalue|" $filename
          fi
        }

        sonarToken=${SONAR_TOKEN}
        if [[ -n "$(params.SONAR_TOKEN)" ]]; then
            sonarToken=$(params.SONAR_TOKEN)
        fi

        sonarSettingsPath=$(workspaces.source.path)/$(params.CONTEXT_DIR)/sonar-project.properties
        
        if [[ -f $(workspaces.sonar-settings.path)/sonar-project.properties ]]; then
          echo "using user provided sonar-project.properties file"
          cp -RL $(workspaces.sonar-settings.path)/sonar-project.properties $sonarSettingsPath
        fi

        if [[ -f $sonarSettingsPath ]]; then
          if [[ -n "$(params.SONAR_HOST_URL)" ]]; then
            replaceValues $sonarSettingsPath sonar.host.url $(params.SONAR_HOST_URL)
          fi
          if [[ -n "$(params.SONAR_PROJECT_KEY)" ]]; then
            replaceValues $sonarSettingsPath sonar.projectKey $(params.SONAR_PROJECT_KEY)
          fi
          if [[ -n "$sonarToken" ]]; then
            replaceValues $sonarSettingsPath sonar.login $sonarToken
          fi
        else
          touch sonar-project.properties
          echo "sonar.projectKey=$(params.SONAR_PROJECT_KEY)" >> sonar-project.properties
          echo "sonar.host.url=$(params.SONAR_HOST_URL)" >> sonar-project.properties
          echo "sonar.login=$sonarToken" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
        fi

        echo "# Updated $(date '+%Y-%m-%d %H:%M:%S')" >> sonar-project.properties

        echo "---------------------------"
        #cat $sonarSettingsPath
        
    - name: sonar-scan
      image: docker.io/sonarsource/sonar-scanner-cli:4.5@sha256:b8c95a37025f3c13162118cd55761ea0b2a13d1837f9deec51b7b6d82c52040a #tag: 4.5
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command:
        - sonar-scanner
      args:
        - "-Dproject.settings=$(workspaces.source.path)/$(params.CONTEXT_DIR)/sonar-project.properties"
